name: Hello World

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Dire bonjour
        run: echo "BONJOUR GITHUB ACTIONNNN ZIOOOON"

      - name: Afficher les infos du contexte
        run: |
          echo "Repository ${{ github.repository }}"
          echo "Branche: ${{ github.ref_name }}"
          echo "Auteur du commit: ${{ github.actor }}"
          echo ${{ secrets.TOKEN }} | base64